#!/bin/bash

#PBS -N DCL_num_Super-Ohmic_T=2
#PBS -l nodes=1:ppn=16:turtle
#PBS -q batch
#PBS -m abe
#PBS -M tommy_lin@berkeley.edu

source /opt/intel/oneapi/setvars.sh

cd $PBS_O_WORKDIR
baseDir=$PBS_O_WORKDIR
echo $HOSTNAME
echo $baseDir
scratchDir="/scratch/tommylin/md_harmonic"

mkdir -p $scratchDir
cd $scratchDir
rm -r * 
cd $baseDir
cp -r * $scratchDir

cd $scratchDir
./md_run.exe
cp -r * $baseDir

