#!/bin/bash

#PBS -N test
#PBS -l nodes=1:ppn=1:turtle
#PBS -q batch
#PBS -m abe
#PBS -M tommy_lin@berkeley.edu

source /opt/intel/oneapi/setvars.sh

cd $PBS_O_WORKDIR
baseDir=$PBS_O_WORKDIR
echo $HOSTNAME
echo $baseDir
scratchDir="/scratch/tommylin/spectrum_nanocrystal/one_mode"

mkdir -p $scratchDir
cd $scratchDir
rm -r * 
cd $baseDir
cp -r * $scratchDir

cd $scratchDir
python3 QM.py
cp -r * $baseDir

