#!/bin/bash

#PBS -N linewidth_E17
#PBS -l nodes=1:ppn=16:chicken
#PBS -q batch
#PBS -m abe
#PBS -M tommy_lin@berkeley.edu

source /opt/intel/oneapi/setvars.sh

cd $PBS_O_WORKDIR
baseDir=$PBS_O_WORKDIR
echo $HOSTNAME
echo $baseDir
scratchDir="/scratch/tommylin/analytical/linewidth_E17"

mkdir -p $scratchDir
cd $scratchDir
rm -r * 
cd $baseDir
cp -r *.py $scratchDir

cd $scratchDir
python3 linewidth_E17.py
cp -r * $baseDir

