#!/bin/bash

#PBS -N 2.2nmCdSe_spectrum
#PBS -l nodes=1:ppn=16:turtle
#PBS -q batch
#PBS -m abe
#PBS -M tommy_lin@berkeley.edu

source /opt/intel/oneapi/setvars.sh

cd $PBS_O_WORKDIR
baseDir=$PBS_O_WORKDIR
echo $HOSTNAME
echo $baseDir
scratchDir="/scratch/tommylin/2.2nmCdSe_spectrum"

mkdir -p $scratchDir
cd $scratchDir
rm -r * 
cd $baseDir
cp -r * $scratchDir

cd $scratchDir
python3 spectrum_T_width.py
cp -r * $baseDir

