#!/bin/bash

#PBS -N Classical_F_spectrum
#PBS -l nodes=1:ppn=16:chicken
#PBS -q batch
#PBS -m abe
#PBS -M tommy_lin@berkeley.edu

source /opt/intel/oneapi/setvars.sh

cd $PBS_O_WORKDIR
baseDir=$PBS_O_WORKDIR
echo $HOSTNAME
echo $baseDir
scratchDir="/scratch/tommylin/spectrum_nanocrystal/Classical_F_spectrum"

mkdir -p $scratchDir
cd $scratchDir
rm -r * 
cd $baseDir
cp -r * $scratchDir

cd $scratchDir
python3 Classical_F_spectrum.py
cp -r * $baseDir

